- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/LinkMetadata.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/LinkMetadataTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- 링크 메타데이터 도메인 엔티티 개발
- 북마크 -> 링크 메타 데이터 1 : N 으로 하였고
- 기존 만들었던 URL vo 를 링크 메타 데이터 엔티티에서 사용하도록 옮겼습니다.
> [LO-20] 링크 메타데이터 도메인 엔티티 개발

- build.gradle
- src/test/java/com/meoguri/linkocean/common/DependencyRuleTest.java
- ArchUnit 추가
-  Naver D2 - <a href="https://d2.naver.com/helloworld/9222129">ArchUnit - UnitTest로 아키텍처 검사</a>
- 여기 보고 참고해서 추가하였습니다.
- 컨트롤러 -> 서비스 -> 리포지토리를 꼭 만족해야하며 계층을 건너 뛰지 않고 거꾸로 접근 하지 않는 것을 테스트합니다.
- infrastrucutre 패키지가 domain 에 접근하지 않는 것을 테스트합니다.
> [LO-26] 의존성 테스트 추가

- .gitignore
- build.gradle
- src/test/java/com/meoguri/linkocean/common/CustomP6spySqlFormat.java
- src/test/java/com/meoguri/linkocean/common/P6spyLogMessageFormatConfiguration.java
- src/test/resources/application.yml
- 테스트 코드에서 p6Spy 추가하였습니다.
- 이에 따라 하이버네이트 로그 설정은 지웠습니다. 테스트 로그를 보고 싶은 경우 `@Import(P6spyLogMessageFormatConfiguration.class)` 를 테스트 클래스에 추가해주면 ? placeholder 를 잘 채워준 로그를 볼 수 있습니다.
> [LO-27] p6Spy 추가

- src/main/java/com/meoguri/linkocean/domain/linkmetadata/scheduler/LinkMetadataSynchronizeScheduler.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataService.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
- 기존 구현은 `LinkMetadataServiceImpl` 에서 `entityManager`에 의존하는 아쉬움이 있었습니다.
- 이를 해결하기위해 스케줄러에서 `while loop` 을 돌아 page 단위로 링크 메타데이터가 업데이트되도록 수정했습니다. 
@jk05018 @ndy2
> [LO-36] 링크 메타데이터 동기화 기능 리펙토링

- .github/workflows/test-every-pull-request.yml
- src/test/java/com/meoguri/linkocean/LinkoceanApplicationTests.java
- `contextLoad` 테스트는 `local` 프로파일에서 수행하도록 수정
- `github actions`에서도 `flyway` `migration`이 잘 되었는지 테스트 할 수 있습니다! 
> [LO-72] contextLoad 테스트는 local 프로파일에서 수행하도록 수정

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTag.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetMyTagsResult.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- 태그 목록 조회 초벌
- 북마크를 전부 끌어와서 애플리케이션 로직에서 태그기준으로 나열 후 카운트를 세 주는것이 나을거 같아 그 방법으로 구현하려고 합니다.
- 영속성 계층 구현하였고 서비스 계층은 아직입니다.
> [LO-81] 태그 목록 조회 초벌

- build.gradle
- src/main/java/com/meoguri/linkocean/configuration/security/SecurityConfiguration.java
- src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomAuthenticationEntryPoint.java
- src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
- src/main/java/com/meoguri/linkocean/configuration/security/oauth/SessionUser.java
- src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
- src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
- security-config 설정 변경
- 권한 없는 사용자를 controllerAdvice가 잡지 못하는 이슈 발생
- @WithMockUser 어노테이션 추가 
자세한 내용은 해당 커밋에 잘 남겨 두었습니다.
- 원래 authenticationENtiryPoint에서 잘 살펴보시면 ObjectMapper.createNode() 를 통해 json을 만들어 내고 있는 것을 보실 수 있습니다. 처음에는 CUstomControllerAdvice.ErrorResponse를 참조하려다가 dependencyTest에서 걸리더군요!
혹시나 이거 ErrorResponse를 참조하면 되지 않을까 궁금하신 분들이 있으실 것 같아서!
@NewEgoDoc, @hyuk0309
> [LO-53] security 설정 및 이슈 해결, 앞으로 ControllerTest에선 @WithMockUser를!

- src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/RegisterBookmarkRequest.java
- src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
- src/main/java/com/meoguri/linkocean/controller/linkmetadata/dto/LinkMetadataTitleResponse.java
- src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
- src/main/java/com/meoguri/linkocean/controller/profile/dto/GetMyProfileResponse.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/dto/GetMyProfileResult.java
- src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategoryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- Category 목록 영어 -> 한글로 리팩터링, 파급효과 정리
- 게시글이 존재하는 카테고리 조회 서비스 개발 & 내 정보 조회 보시면 됩니다!
- 링크_메타데이터_조회 Controller Test
- 북마크 생성 Controller Test
- 내정보 조회 Controller Test
- 
@ndy2 , @NewEgoDoc, @hyuk0309
> [LO-52] 내정보 조회(사용자 태그목록, 카테고리 목록 추가) 외 다양한 작업들

- src/main/java/com/meoguri/linkocean/configuration/DateFormatConfig.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarkResponse.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- 북마크 제목, 메모, 카테고리 `null`인 경우 `NPE` 이슈 해결
- `bookmark` 엔티티에서 `null`을 허용하는 필드들은 `getter`을 명시적으로 만들고, `null`인 경우 `""`을 반환하도록 수정했습니다.
- 관련 테스트 코드를 작성했습니다. 테스트 코드를 작성하면 `BaseControllerTest`의 `북마크_등록 API`를 활용하려 했지만 저장한 북마크의 식별번호를 알 수 없어 사용하지 못했습니다.
> [LO-97] 북마크 제목, 메모, 카테고리 Null인 경우 NPE 이슈 해결

- src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/TagController.java
- src/main/java/com/meoguri/linkocean/controller/category/CategoryController.java
- src/main/java/com/meoguri/linkocean/controller/common/PageResponse.java
- src/main/java/com/meoguri/linkocean/controller/common/PageResponseJsonSerializer.java
- src/main/java/com/meoguri/linkocean/controller/common/SliceResponse.java
- src/main/java/com/meoguri/linkocean/controller/common/SliceResponseJsonSerializer.java
- src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
- src/main/java/com/meoguri/linkocean/controller/profile/dto/GetProfilesResponse.java
- src/main/java/com/meoguri/linkocean/controller/profile/support/GetProfileQueryParams.java
- src/main/java/com/meoguri/linkocean/controller/profile/support/GetProfileQueryParamsArgumentResolver.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
- 프로필 목록 조회 - 머구리 찾기 컨트롤러
- 기존 ListResponse 를 PageResponse 로 이름을 바꾸고 total count 가 필요 없는 페이지 (slice) 요청에 대한 array 를 wrapping 하는 SliceResponse 를 PageResponse 와 같은 방식으로 구현하였습니다.
- 목록 json 응답에 대해 hasItems 적용하면 좋을것 같습니다. 순서가 보장되지 않아도 적용 가능하네요
> [LO-103] 프로필 목록 조회 - 머구리 찾기

- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- 북마크 상세 조회 컨트롤러 & 서비스 개발
- 북마크 상세 조회 `API`에 내려줘야 하는 데이터가 추가돼 컨트롤러와 서비스를 수정했습니다.
- 북마크 상세 조회에서 북마크 좋아요 개수를 가져와야하는데 아직은 `count` 쿼리를 이용합니다. (추후 리액션 요청의 수정사항이 생기면 수정하겠습니다.)
> [LO-104] 북마크 상세 조회 컨트롤러 & 서비스 개발

- src/main/java/com/meoguri/linkocean/controller/notification/NotificationController.java
- src/main/java/com/meoguri/linkocean/controller/notification/dto/ShareNotificationRequest.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationService.java
- src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
- 컨트롤러에서도 서비스에서처럼 일단은 엔티티를 반환하는 방식으로 구현했고 의도한 대로 동작은 하는데
ObjectId 로 선언된 불필요한 정보들이 함께 나가고 Json 필드의 값을 맞추기 위해서 Jackson 의 어노테이션들이 도메인 영역까지 침투하는 문제가 생길거 같네요...
일단은 이렇게 구현하였습니다.
- 서비스에서 공유 알림 생성시 남의 게시글에 대해서 막는 검증이 빠져있어서 추가하였습니다.
- 일단은 mongoDB docker 로 진행하고 차차 api 가 하나씩 완성되고 여유가 되면 aws document db 로 옮겨보겠습니다.
> [LO-67] 공유 알림 생성, 알림 목록 조회 컨트롤러 

- src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParams.java
- src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParamsArgumentResolver.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/FindBookmarksDefaultCond.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/MyBookmarkSearchCond.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/OtherBookmarkSearchCond.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFavoriteQuery.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepository.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/dto/ProfileFindCond.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
- src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
- 페이지 리팩토링이 커질거 같아서 한번에 머지하는거는 좀 어렵고 브랜치를 하나 파서 추후에 합치는것이 필요해 보입니다.
- Spring Page,Pagable 을 전역적으로 사용하면서 응답시에만 PageResponse 를 사용하는 방향으로 생각중입니다.
- Pagable 에 paging 과 관련된 page, size, order 를 넘기고 검색, 조회 조건에는 이를 제외할 계획입니다.
현재 page, size 의 이주를 마쳤고 order 는 진행 예정입니다.
---
- 서비스 계층에서는 검색(search) 영속성 계층에서는 조회 (find) 라는 용어로 미는 방향을 생각중입니다.
- 그리고 @Query 도 전에 재사용성을 고려해 도입한다고 예기가 됬는데 어제 이야기 하였듯이 작업의 규모가 크고 한 덩어리로 처리되는 느낌이 강하다면 @Query 를 적용하는것이 좋아보입니다. 이예따라 CheckIsFavoriteQuery를 추가하였고 ReactionMap 시리즈를 조회하기 위한 ReactionQuery 도 추가해 checkReaction, countReaction 이런 애들을 추가할 생각입니다. 
---
변경이 너무 많아 테스트를 다 지키면서 가기 힘들어 일단 내 북마크 목록 조회에 대해서만 진행하였고 추후
다른 사람 북마크 조회, 정렬 적용, paging 처리 코드 개선 등의 작업을 진행 할 수  있을것 같습니다.
--
그리고 검색조건에 대한 검증을 커맨드나 Request 로 뺐을때 3항연산자를 통해 코드가 훨씬 이쁘게 나올것 같아서 일단 빼 보았습니다.
아직 검증의 적용은 하지 않았습니다
빠르게 달리다보니 …
> [LO-115] 내 북마크 조회 리팩토링

- README.md
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/UltimateBookmarkFindCond.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/util/JoinInfo.java
- src/main/java/com/meoguri/linkocean/util/JoinInfoListBuilder.java
- src/main/java/com/meoguri/linkocean/util/QueryDslUtil.java
- joinIf 강화, 북마크 조회 통합 초벌
- 북마크 구현시 아무래도 동적 join 을 다양하게 구사 할것 같아서 기존의 joinIf 로직을 강화시켰습니다.
- 기존에 한번쓰고 치울 생각으로 처리했던 파라미터 타입에 대해서만, chaining 도 없이 단순 하게 구현했었는데
querydsl 에서 join. 해서 나오는 모든 타입을 핸들링 할 수 있도록 했고 빌더패턴으로 메서드 체이닝을 가능하게 하여 join 여러개 체이닝, fetchJoin 적용등을 가능하게 하였습니다. 
---
- 기존의 프로필 조회에서는 잘 동작하는것을 확인 하였습니다.
- 아직 더 다양한 상황에서의 테스트는 안해봤는데 궁극의 북마크 조회 로직 개발이 기대되네요
> [LO-118] joinIf 강화, 북마크 조회 통합 초벌

- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- 중복 url 관련 repository method에서 Optional<Bookmark> 반환으로 변경하였습니다. 이에 따라 test 검증도 optional 검증으로 변경하였습니다.
- 중복 url 관련 service에서 repository 변경에 따라 Optional<Bookmark> 반환으로 변경하였습니다.
- 중복 url controller 리팩토링이 있었으며 관련 반대 test case 추가 및 header 검증 추가하였습니다.
- 현재 중복 URL API는 userId 를 사용하기 때문에 차후에 profileId 사용으로 변경하겠습니다.
> [LO-77] 중복 URL 확인 API 변경

- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepository.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/dto/UltimateProfileFindCond.java
- src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
- 프로필 목록 조회 영속성 계층 리팩토링
- 기존에 3개로 나윘었던 프로필 목록 조회 영속성 API들을 하나로 합쳤습니다. (팔로워 목록 조회, 팔로이 목록 조회, 이름으로 프로필 목록 검색)
- @Disable로 표시된 테스트는 리팩토링이 완료되면 제거될 친구들입니다.
- 프로필 목록 조회 조인에서 삽질해서 생각보다 오래걸렸네요. ㅎㅎ
> [LO-133] 프로필 목록 조회 영속성 계층 리팩토링

- build.gradle
- docs/asciidoc/FOLLOW-API.adoc
- docs/asciidoc/LINKMETADATA-API.adoc
- docs/asciidoc/LOGIN-API.adoc
- docs/asciidoc/NOTIFICATION-API.adoc
- docs/asciidoc/PROFILE_API.adoc
- docs/asciidoc/index.adoc
- src/test/java/com/meoguri/linkocean/controller/restdocs/FollowDocsController.java
- src/test/java/com/meoguri/linkocean/controller/restdocs/LinkMetadataDocsController.java
- src/test/java/com/meoguri/linkocean/controller/restdocs/LoginDocsController.java
- src/test/java/com/meoguri/linkocean/controller/restdocs/NotificationDocsController.java
- src/test/java/com/meoguri/linkocean/controller/restdocs/ProfileDocsController.java
- login, follow, notification, linkMetadata, profile restdocs 추가
- 처음에 저희 ControllerTest에 바로 RestDocs를 적용하려 했습니다.
- 하지만 적용하려보니 다양한 문제점이 있었습니다. 이 부분에 대해서는 내일 만나서 설명드리겠습니다.
- 따라서 ~DocsController를 만들고 RestDocs 작업을 진행하였습니다.
추가) 저희 API Document 최신화 아주 많이 안되어 있더군요 ㅎㄷㄷ 이걸로 작업하신 프론트엔드가 대단하다 느끼는 하루였습니다 😢 
또 추가) 저희 DocsController는 평소에 Disable하고있다가 docs를 최신화할 때 풀어주는 방식으로 진행해도 될 것 같습니다.
@ndy2 ,@NewEgoDoc, @hyuk0309
> [LO-156] login, follow, notification, linkMetadata, profile restdocs 추가

- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/Link.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
- 링크 메타데이터 저장시 http(s) & www 제거하는 로직 제거하기
-  기존에는 linkmetadata의 link 저장 과정에서 입력 받은 link를  그대로 저장하는게 아니라 http(s) & www를 제거하고 저장했습니다.
-  처음에는 위 로직이 데이터 중복을 줄여 좋을지 알았는데, link에 너무 많은 경우의 수가 있어 버그가 생겼습니다.
-  따라서 데이터를 전처리하지 않고 그대로 저장하는 방식으로 수정했습니다.
> [LO-158] 링크 메타데이터 저장시 http(s) & www 제거하는 로직 제거하기

- src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
- src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
- 링크 메타데이터 제목 조회 API 수정
- 링크 메타데이터 제목 조회 API에서 문제를 발견했습니다. 
- url을 쿼리 파라미터로 받다보니, url에 `&`가 있으면 뒤에 있는 문자열들이 짤리는 것 같습니다.
- 이를 해결하기 위해서는 url을 쿼리 파라미터가 아니라, request body로 받아야 할 것 같아요. 마침 링크 메타데이터 제목 조회 API도 POST고요!
- (중요!!) 아직 머지하면 안됩니다. 프론트 분들 의견 들어보고 합의되면 머지하겠습니다~
> [LO-157] 링크 메타데이터 제목 조회 API 수정

- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
- src/main/java/com/meoguri/linkocean/util/querydsl/Join.java
- src/main/java/com/meoguri/linkocean/util/querydsl/JoinInfoBuilder.java
- src/main/java/com/meoguri/linkocean/util/querydsl/Querydsl4RepositorySupport.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- 북마크 목록 조회 카운트 쿼리 최적화
- count query 에 대해서 join 을 날리지 않도록 바꾸었습니다.
단순하게 바꾸면 코드 중복이 심해질 것 같아서 applyPaganation 을 좀 더 커스터마이징 했습니다.
이제 코드가 훨씬 더 sql 같이 읽히고 볼만해 졌습니다 !
> [LO-181] 북마크 목록 조회 카운트 쿼리 최적화

- env/mysql.env
- src/test/resources/application.yml
- Local Test DB 이름 변경
- 테스트 DB를 MySQL로 바꾸면서 기존 도커 DB 이름이 Linkoceantest로 바꿨습니다. 그런데 생각해보니까 local에서는 하나의 디비로 test도 하고 local에서 돌려보는 용도로 사용하는게 좋을 것 같아 이름을 Linkocean으로 바꿨습니다! (flyway 설정 파일에도 아직 linkocean으로 남아 있더라고요. 그래서 둘로 나눌까 고민했는데 나누는건 과한 것 같아 이렇게 바꿨습니다. 테스트할때는 데이터를 세팅하고 밀어주는 작업이 기본으로 들어가기 때문에 Local에서 같은 DB로 테스트하는것도 문제 없을 것 같아요.~)
> [LO-183] Local Test DB 이름 변경

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteBookmarkIds.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Reaction.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Reactions.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQuery.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepository.java
- src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
- src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
- @Entity 북마크.리액션 deprecation -> @ElementCollection 프로필.리액션
- 리액션 요청 (등록) 및 리액션 카운트 맵 퍼올리기 
까지 ElementCollection 으로 처리하도록 변경 하였습니다.
- 이후 리액션 여부 확인 만 이주시키면 Reaction, ReactionRepository, ReactionQuery 시리즈 다 없앨 수 있을것 같습니다.
이 과정에서 상세조회의 경우 영속성에서 dto 를 퍼올리도록 변경 될 수도 있을것 같습니다.
메서드 시그니처를 어떻게 가져가야 할지 고민이네요
> [LO-182] WIP @Entity 북마크.리액션 deprecation -> @ElementCollection 프로필.리액션

- build.gradle
- api 문서 jar에 말기
- ascidoctor로 만든 api 문서가 jar 파일에 포함되지 않는 이슈가 있어 해결했어요.
- 추가로 gradle.build 파일이 build 순서를 잘 표현하게 리펙토링 했어요.
- @ndy2 하하 로컬 JDK 스펙 여기에 남겨주세요!! 😄 
> [LO-198] api 문서 jar에 말기

- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/Link.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/vo/LinkTest.java
- jsoup 이슈 해결
- 링크 메타데이터 제목 조회 API에서 예상과 다르게 400 상태 코드를 반환하는 이슈가 있어서 해결했습니다. 원인은 url 정규식이 좁은 범위의 url 포맷만 허용해줘서 그랬습니다.  
<hr/>
링크 메타데이터 관련 이슈를 해결하면서 수정하면 더 좋아질 부분들이 보여 제가 추가로 작업하겠습니다. 
1. 북마크 엔티티에서 링크 메타데이터 엔티티를 참조하고 있습니다. 그런데 북마크와 링크 메타데이터는 다른 에그리거트이므로 좋지 않은 설계같습니다. 
따라서 북마크 엔티티에서 링크 메타데이터 ID만 참조하도록 변경할 예정입니다.
2. 정책적으로 북마크는 무조건 링크 메타데이터 아이디를 외래키로 가져야 합니다. 그런데 생각해보니까 북마크 url에 제대로된 링크 메타데이터가 존재하지 않다면, 의미가 없는 참조같다는 생각이 들었습니다. 이로 인해 링크 메타데이터 테이블에도 필요없는 데이터가 쌓이는 것 같아요. 
따라서 북마크에서 링크 메타데이터 아이디를 갖지만 null도 허용하게 바꿀 생각입니다. 추가로 링크 메타데이터 타이틀 조회시에도 링크 메타데이터가 존재하지 않으면 db에 저장하지 않을 생각입니다. 
> [LO-202] jsoup 이슈 해결

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByIdQuery.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepository.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/command/entity/ProfileTest.java
- src/test/java/com/meoguri/linkocean/test/support/domain/entity/BaseEntityTest.java
- src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
- 북마크 링크메타데이터 ID 참조
- 에그리거트끼리 엔티티로 의존관계를 맺으면 JPA의 편리한 기능을 사용할 수 있지만, 에그리거트끼리 결합도가 높아져 여러 단점이 존재합니다. 대안으로 에그리거트 사이의 의존관계를 식별자를 통해 맺을 수 있습니다. 그러면 결합도가 낮아져 여러 단점들이 해소됩니다. 
- 위의 이유로 북마크에서 링크 메타데이터의 아이디를 식별하도록 바꿨습니다. 
- 진행하면서 큰 사이드 이팩트는 북마크 조회 로직에서 기존에는 폐치 조인을 이용해 링크 메타데이터를 땡겨왔는데 그렇게 하지 못하기때문에 서비스 에서 링크 메타데이터 집합을 가져와 말아주는 방식으로 변경했습니다. 
- DDD책 아주 나이스네요! ㅎㅎ 😄 
> [LO-203] 북마크 링크메타데이터 ID 참조

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByUrlQuery.java
- src/main/resources/db/migration/V021__Alter_bookmark.sql
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/command/service/FavoriteServiceImplTest.java
- src/test/java/com/meoguri/linkocean/test/support/domain/service/BaseServiceTest.java
- 북마크 생성 정책 변경
- 북마크 생성시 북마크 url에 링크 메타데이터가 존재하지 않아도 저장 가능하도록 변경한 정책을 코드에 반영했습니다.
- 정책이 변경되면서 변경된 부분입니다.
- 북마크 테이블 link_metadata_id에 not null 제약 조건 제거
- 북마크 엔티티 linkmetadata getter optional 추가
- 북마크 생성 서비스 로직 변경
- 북마크 상세 조회, 목록 조회에서 북마크 링크 메타데이터 존재 하지 않으면 서비스에서 DEFAULT_IMAGE 값 넣어주기
- 관련 시나리오 테스트 추가
> [LO-206] 북마크 생성 정책 변경

- src/main/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/GetLinkMetadata.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/dto/GetLinkMetadataResult.java
- src/main/java/com/meoguri/linkocean/infrastructure/jsoup/JsoupGetLinkMetadataService.java
- src/main/java/com/meoguri/linkocean/infrastructure/jsoup/JsoupLinkMetadataService.java
- src/test/java/com/meoguri/linkocean/DependencyRuleTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
- src/test/java/com/meoguri/linkocean/infrastructure/jsoup/JsoupGetLinkMetadataServiceTest.java
- src/test/java/com/meoguri/linkocean/infrastructure/jsoup/JsoupLinkMetadataServiceTest.java
- 링크 메타데이터 정책 변경
- 링크 메타데이터를 조회한 url이 유효하지 않은 경우(Jsoup으로 해당 페이지를 조회하지 못하는 경우) db에 저장하지 않는걸로 정책을 변경했습니다. 
- DIP를 적용해 Jsop이 linkmetadata에 의존하게 변경했습니다. (도메인이 JPA에 의존하는 문제는 JPA라는 기술이 자바 표준이기에 합당한 의존이지만, 도메인이 Jsoup에 의존하는 문제는 Jsoup이라는 기술이 JPA 처럼 표준 기술은 아니기 때문에 DIP를 적용하는게 더 좋다고 판단했습니다.)
<hr/>
- s3는 어떻게 처리할지 고민이네요. 🤔 
> [LO-208] 링크 메타데이터 정책 변경

- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- 북마크 상세 조회 버그 해결
- 다른 사람 북마크 상세 조회시 프로필 응답값이 제대로 내려오지 않는 이슈가 있었어요. ([참조](https://www.notion.so/backend-devcourse/b4824b0a86c04ca392b64fa6c81a7ca3))
- 관련된 테스트가 없어서 테스트 작성해서 이상 없는거 확인 했습니다. (따로 수정한건 없습니다. 리팩토링하면서 잡힌 것 같아요..)
- 북마크 컨트롤러 테스트 리팩토링 했습니다. 
- 테스트 네이밍 통일
- when, then 영역 명확하게 분리 
<hr/>
- controller test 메서드 네이밍이 전반적으로 통일된 것 같지 않네요 ㅎㅎ (api가 붙은 테스트도 있고 없는 테스트도 있네요) 천천히 고치겠습니다.
- controller test 에서도 when, then 영역을 분리하면 좋겠다는 생각이 들어서 명확하게 분리해 봤습니다. 괜찮으면 컨벤션에 추가해도 좋을 것 같아요. ✋ 
> [LO-211] 북마크 상세 조회 버그 해결

- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
- 링크 메타데이터 동기화 버그 해결
-  링크 메타데이터 동기화 시점에 url이 유효하지 않게 바뀌면 (해당 페이지가 사라지면) 예외가 발생해 업데이트가 안되는 이슈 해결
- 관련 테스트 작성
> [LO-212] 링크 메타데이터 동기화 버그 해결

- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/CategoryControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/FavoriteControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/FollowControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
- src/test/java/com/meoguri/linkocean/test/support/controller/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/test/support/controller/ControllerTest.java
- 컨트롤러 테스트 @Transactional 제거 & 컨밴션에 맞게 리팩토링
- Controller 테스트에도 @Transactional을 제거했습니다.
- Controller 테스트 네이밍과, when/then 영역을 구분하는 작업을 했습니다..
- 너무 많은 것을 테스트하는 것 같은 테스트는 여러개의 테스트로 분리했습니다.
<hr/>
- 리팩토링 하다보니까 저희 알림 기능도 진짜 아픈 손가락이네요 ㅎㅎ
- 서비스와 컨트롤러 테스트의 트랜잭션을 제거해 프로덕션 코드와 비슷한 환경이 됐습니다. 하지만 단점으로 테스트 시간이 오래 걸리네요. 이것도 한번 최적화에 대해 공부한 다음 적용해보면 재밌을 것 같아요. 😄 
> [LO-215] 컨트롤러 테스트 @Transactional 제거 & 컨밴션에 맞게 리팩토링

- docker-compose.yml
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/util/querydsl/CustomPath.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
- src/test/java/com/meoguri/linkocean/test/support/domain/service/BaseServiceTest.java
- src/test/java/com/meoguri/linkocean/test/support/logging/p6spy/P6spyLogMessageFormatConfiguration.java
- 내 프로필 조회 태그 데이터 버그 해결
- 내 프로필 목록 조회에 태그 데이터에서 삭제된 북마크도 포함되는 버그가 있었습니다. [참조](https://www.notion.so/backend-devcourse/64b3797f04c34b878a430f21a0bfaf82)
- 관련 쿼리 수정했습니다
- JpasqlQeury를 사용하니까 EnumPath 직렬화를 의도한데로 못해주는 것 같아요 [참조](https://github.com/querydsl/querydsl/issues/419)
- 그래서 StringPath로 우회하는 방법을 사용했습니다.
> [LO-218] 내 프로필 조회 태그 데이터 버그 해결

- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/resources/db/migration/V022__Alter_tag.sql
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/tag/persistence/TagRepositoryTest.java
- src/test/java/com/meoguri/linkocean/test/support/domain/persistence/BasePersistenceTest.java
- src/test/resources/application.yml
- 다른 사람 북마크 목록 조회 태그 필터링 버그 해결
- 다른 사람 북마크 조회시 태그 필터링이 제대로 동작하지 않는 이슈가 있었습니다. [참조](https://www.notion.so/backend-devcourse/fc2d07433c3e420497a5f801246e118b)
- 조인할때 on 절 조건을 빼먹어 카타시안 연산이 적용됐습니다. 이를 알맞게 수정했습니다.
- 관련 테스트도 추가했습니다.
- 추가로 tag 테이블의 collation 변경으로 태그 이름도 대소문자 구분이 가능합니다.
- 테스트 설정에서 ddl-auto를 사용하는 것이 아니라, validate로 바꿨습니다. 이유는 tag 테이블의 name 컬럼의 collation 옵션이 바뀌면서 이를 tag 엔티티에 표시해줄까 고민했습니다. 제가 내린 결론은 코드가 지저분해 지는 것 같아 따로 표시하지 않았습니다. 그래서 jpa가 만들어주는 ddl과 flyway ddl의 차이가 생겼습니다. 그래서 ddl-auto는 제거하고 flyway를 사용하는 방식으로 바꿨습니다.
<hr/>
- 테스트를 나름 꼼꼼히 작성한 것 같은데, 빼먹은 시나리오들이 많네요.. ㅎㅎ 
> [LO-220] 다른 사람 북마크 목록 조회 태그 필터링 버그 해결

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/OpenType.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileQueryRepositoryTest.java
- src/test/java/com/meoguri/linkocean/test/restdocs/BookmarkRestDocsTest.java
- 북마크 오픈타입 정책 변경
- 원래 북마크 오픈타입에는 ALL, PARTIAL, PRIVATE이 있었습니다. PARTIAL은 자신의 팔로워들에게만 북마크 접근을 허용하는 개념이었습니다. 하지만 저희 서비스는 팔로워, 팔로이 정책이기 때문에 아무나 나를 팔로우 할 수 있습니다. 따라서 PARTIAL이 의미가 없고, 오히려 비즈니스 로직만 복잡하게 만들었습니다. 그래서 저번에 팀 회의에서 제거하기로 결정했었습니다.
<hr/>
- 현재 피드 북마크 목록조회, 다른 사람 북마크 목록 조회, 내 북마크 목록 조회를 CustomBookmarkRepositoryImpl의 findBookmarks 메소드에서 해결하고 있습니다. 저희가 초반에는 querydsl의 동적쿼리를 최대한 이용하고, 중복 코드를 없애기 위해 통합했었습니다. 그런데 지금와서 보니까 유지보수 하기 어려운 코드 같다고 느꼈습니다. 북마크 목록 조회와, 피드 북마크 목록조회는 어떻게 보면 다른 기능이라고 생각합니다. 따라서 이를 분리하면 코드 중복이 생길지라도 유지보수와 확장성 측면에서는 더 좋아질 것 같다는 생각을 했습니다. 🤔 
> [LO-222] 북마크 오픈타입 정책 변경

- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
- 링크 메타데이터 동기화 버그 해결
- 버그 이유
- 기존 링크 메타데이터 동기화시, url이 유효하지 않으면 링크 메타데이터 데이터를 지워주는 정책으로 개발했습니다. 이때 발생하는 문제 중 하나가 기존 북마크에서 링크 메타데이터를 외래키고 갖고 있으면 북마크 데이터도 같이 변경해야 합니다.
- 동기화시 url이 유효하지 않은 경우 처리할 수 있는 선택지가 두 가지 있었습니다.
-  링크 메타데이터 지우고, 북마크의 링크 메타데이터 외래키 null로 변경
- 장점 : 데이터가 깔끔하게 지워짐
- 단점 : 사용자 북마크에 있었던 이미지가 갑자기 없어지고, 추후 url이 유효하게 바뀌어도 북마크에 반영되지 않음 
-  기존 값 유지
- 장점 : 갑자기 이미지가 없어지지 않고, 추후 url이 유효하게 바뀌어도 동기화 시점에 북마크에 반영됨
- 단점 : 데이터가 깔끔하게 지워지지 않음 
- 이미 존재했던 url이므로 지금은 유효하지 않더라도 추후에 유효해질 가능성이 있을 것 같고 사용자 입장에서는 갑자기 이미지가 없어지는 경험은 좋지 않을 것 같아 2번 방향으로 구현했습니다.
> [LO-224] 링크 메타데이터 동기화 버그 해결

- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Follow.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/query/persistence/ProfileQueryRepository.java
- src/main/java/com/meoguri/linkocean/domain/profile/query/service/ProfileQueryServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/profile/query/persistence/CustomProfileQueryRepositoryImplTest.java
- follow 에서 id 만 가지게 하기
- fixture monkey 를 테스트 해보고 있는데 프로필 생성에 팔로우가 필요하고 팔로우 생성에 프로필이 필요해서 stack overflow 가 발생하더라고요 fixture monkey 를 잘 쓰면 적절 하게 탐색하거나 null 을 바인딩 해주는 방법으로 해결 할 수는 있겠지만 저는 뉴비기도 하고 해서 
follow 에 profile 참조가 필요한가 살펴 보았는데 사용되는 곳이 없더라고요
그래서 id 만 가지도록 변경하였습니다.
- 변경 하면서 profile 조회의 joinIf 구문을 없앴습니다. 찬찬히 보니까 join 이 필요 없는 로직 이었어요
> [LO-223] follow 에서 id 만 가지게 하기

- src/docs/asciidoc/api/Auth-API.adoc
- src/main/java/com/meoguri/linkocean/controller/user/AuthController.java
- src/main/java/com/meoguri/linkocean/controller/user/dto/AuthRequest.java
- src/main/java/com/meoguri/linkocean/domain/user/service/OAuthAuthenticationService.java
- src/main/java/com/meoguri/linkocean/domain/user/service/OAuthClient.java
- src/main/java/com/meoguri/linkocean/infrastructure/oauth/google/GoogleOAuthClient.java
- src/main/java/com/meoguri/linkocean/infrastructure/oauth/google/GoogleOAuthProperties.java
- src/test/java/com/meoguri/linkocean/controller/user/AuthControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/user/service/OAuthAuthenticationServiceTest.java
- src/test/java/com/meoguri/linkocean/infrastructure/oauth/google/GoogleOAuthClientTest.java
- src/test/java/com/meoguri/linkocean/test/restdocs/AuthRestDocsTest.java
- 소셜 로그인 API 스펙 변경
- 인증 요청시 redirect uri 정보도 보내도록 API 스펙 변경했습니다.
- 저희의 로그인 플로우상 redirect uri는 프론트에서 정합니다. 따라서 해당 정보도 인증 요청시 인증 코드와 같이 받는게 적절하다고 판단돼 API 스펙을 변경했습니다.
> [LO-228] 소셜 로그인 API 스펙 변경

- .github/workflows/dev-ci-cd.yml
- .github/workflows/prod-ci-cd.yml
- 배포, 운영 CI-CD 수정
- CI-CD 프로세스에서 `docker remove -f $(docker ps -aq)`를 `docker remove -f linkocean-spring`로 수정했습니다. 왜냐하면 개발, 운영 서버에 redis도 실행되고 있기 때문입니다.
@ndy2
> [LO-232] 배포, 운영 CI-CD 수정

- src/docs/asciidoc/api/Auth-API.adoc
- src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtProperties.java
- src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtProvider.java
- src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
- src/main/java/com/meoguri/linkocean/controller/user/AuthController.java
- src/main/java/com/meoguri/linkocean/controller/user/dto/RefreshAccessTokenRequest.java
- src/main/java/com/meoguri/linkocean/internal/user/application/OAuthAuthenticationService.java
- src/main/java/com/meoguri/linkocean/internal/user/application/RefreshTokenService.java
- src/main/java/com/meoguri/linkocean/internal/user/application/dto/GetAuthTokenResult.java
- src/main/java/com/meoguri/linkocean/internal/user/domain/UserService.java
- src/main/java/com/meoguri/linkocean/internal/user/domain/UserServiceImpl.java
- src/main/java/com/meoguri/linkocean/internal/user/infrastructure/redis/RedisRefreshTokenService.java
- src/main/java/com/meoguri/linkocean/internal/user/infrastructure/redis/RefreshToken.java
- src/test/java/com/meoguri/linkocean/configuration/security/jwt/JwtProviderTest.java
- src/test/java/com/meoguri/linkocean/controller/user/AuthControllerTest.java
- src/test/java/com/meoguri/linkocean/internal/user/application/OAuthAuthenticationServiceTest.java
- src/test/java/com/meoguri/linkocean/internal/user/domain/UserServiceImplTest.java
- src/test/java/com/meoguri/linkocean/internal/user/infrastructure/redis/RedisRefreshTokenServiceTest.java
- src/test/java/com/meoguri/linkocean/test/restdocs/AuthRestDocsTest.java
- src/test/java/com/meoguri/linkocean/test/support/controller/BaseControllerTest.java
- src/test/resources/application.yml
- access token 재발급 API 개발
- access token의 만료일은 10시간, refresh token의 만료일은 7일로 설정했습니다.
- refresh token의 유효기간이 길어 탈취 위험성이 있기 때문에 refresh token rotation, refresh token automatic reuse detection을 적용했습니다. ([참조](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/#Refresh-Token-Automatic-Reuse-Detection))
- 기존에는 Jwt 파싱 과정에서 예외가 발생하면 LinkoceanRuntimeException으로 처리했는데, 이를 JwtException으로 바꾸고 핸들러에서 따로 처리하도록 개발했습니다. 이제는 401 상태를 반환합니다. 
- Test 관련해서는 Service 테스트에서는 OAuthClient, RefreshTokenService 컴포넌트는 외부 컨포넌트라고 가정하고 모킹했습니다. 하지만 Controller 테스트에서는 Redis는 직접 사용했습니다. 완전 통합 테스트라 가정해 프로덕션 환경과 맞출 수 있는 부분은 최대한 맞췄습니다. (OAuthClient는 Jsoup과 동일하게 네트워크 통신이 필요한 API이기 때문에 완전 통합 테스트에서도 모킹했습니다.)
@ndy2
> [LO-231] access token 재발급 API 개발
