prgrms-web-devcourse/Team-Meoguri-Linkocean-BE

- README.md
> [LO-6] 워크 플로우 트리거 테스트

- build.gradle
- src/main/java/com/meoguri/linkocean/domain/common/BaseIdEntity.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/OAuthType.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
> [LO-6] 사용자 도메인 모델 개발

- build.gradle
- config/checkstyle/naver-checkstyle-rules.xml
- config/checkstyle/naver-intellij-formatter.xml
- src/main/java/com/meoguri/linkocean/LinkoceanApplication.java
- src/main/java/com/meoguri/linkocean/domain/common/BaseIdEntity.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/OAuthType.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/test/java/com/meoguri/linkocean/LinkoceanApplicationTests.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- 코딩 컨벤션 설정 파일 추가
- 빌드 스크립트에 체크 스타일 플러그인 추가
-  기존코드를 체크 스타일에 맞게 리펙토링 했습니다.
> [LO-11] 코딩 컨벤션 설정

- build.gradle
- src/main/java/com/meoguri/linkocean/LinkoceanApplication.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
- final 키워드 삽입, @Column 자세하게 작성, 이메일 검증
> [LO-10] 회원 기능 도메인

- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
> [LO-12] 프로필 기능 도메인

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/OpenType.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Url.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/main/resources/application.yml
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/UrlTest.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- 북마크 도메인 개발
- 회원, 프로파일 도메인 리펙토링
> [LO-13] 북마크 도메인 개발

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Url.java
- src/main/java/com/meoguri/linkocean/domain/common/Preconditions.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
> [LO-14] 예외처리 로직 빼기

- src/main/java/com/meoguri/linkocean/domain/follow/entity/Follow.java
- src/test/java/com/meoguri/linkocean/domain/follow/entity/FollowTest.java
> [LO-15] 팔로우 엔티티 개발

- src/main/java/com/meoguri/linkocean/domain/category/entity/Category.java
- src/main/java/com/meoguri/linkocean/domain/category/entity/FavoriteCategory.java
- category 엔티티 개발
- favoriteCategory 엔티티 개발
> [LO-17] 카테고리 도메인 엔티티 개발

- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/vo/Email.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/vo/OAuthType.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/vo/EmailTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
> [LO-18] 패키지 대이동2

- src/main/java/com/meoguri/linkocean/exception/Preconditions.java
> [LO-19] Preconditions 리팩토링

- build.gradle
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
- local에서 h2 데이터베이스 환경이 필요하지 않음에 따라 dependency 를 삭제하였습니다
-  application.yml을 추가 하였습니다 (test, local)
> [LO-23] application yml 설정 + h2 데이터베이스 환경 삭제

- build.gradle
- src/test/resources/application.yml
> [HotFix] Test DB는 H2 DB 바라보도록 수정

- src/main/resources/db/migration/V013__ALTER_reaction.sql
- src/test/java/com/meoguri/linkocean/domain/bookmark/repository/ReactionRepositoryTest.java
- flyway V13 alter reaction
- add column & fk constraint
> [LO-35] flyway V13 alter reaction

- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/GetBookmarkByIdQuery.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/category/persistence/CategoryRepository.java
- src/main/java/com/meoguri/linkocean/domain/category/persistence/FavoriteCategoryRepository.java
- src/main/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepository.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/GetProfileByUserIdQuery.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepository.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/GetBookmarkByIdQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/category/persistence/CategoryRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/category/service/CategoryServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/category/service/FavoriteCategoryServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/GetProfileByUserIdQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
- 영속성 패키지 이름 변경
- Query 영속성 패키지로 이동
> [LO-38] 영속성 패키지 이름 변경, Query 영속성 패키지로 이동

- build.gradle
- src/main/java/com/meoguri/linkocean/IndexController.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
- flyway-mysql 의존성으로 인한 빌드 깨짐 해결
- application local, dev 설정 추가 및 보완
- 배포용 healthcheck url 추가
- 로컬 개발 환경에 대한 토의가 필요 해 보입니다!
@ndy2, @NewEgoDoc
> [LO-40] flyway build 깨짐 해결 및 local, dev 환경설정 추가 및 보완

- build.gradle
- h2database -> testImplementation, config create -> validate
> [LO-45] h2database -> testImplementation, config create -> validate

- src/main/java/com/meoguri/linkocean/controller/CustomControllerAdvice.java
- CustomControllerAdvice 초벌 추가 -> 나중에 저희 가 발생시키는 예외에 대해서 추가 및 삭제하면 될 것 같습니다.
- 
@NewEgoDoc, @hyuk0309
> [LO-70] CustomControllerAdvice 초벌 추가

- .gitignore
> [LO-71] .gitignore에 설정 파일 추가하기

- checkstyle/naver-checkstyle-rules.xml
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/category/CategoryControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImplTest.java
- 팔로워/팔로이 목록 조회 서비스 마무리
- 크러쉬 말대로 casecade, orphan removal 추가하여 버그 픽스하였습니다.
- 테스트에서 @Nested 도입해서 클래스 이름에도 한글이 쓰고 싶어져서 check-style rule 을 변경하였습니다. 대신 전에 약어 사용을 풀었던 부분을 다시 제한 하였습니다.
- CODEOWERS 적용한게 또 안되네요.. 수동 추가했습니다.
@jk05018 , @NewEgoDoc
> [LO-76] 팔로워/팔로이 목록 조회 서비스 마무리

- .github/workflows/test-every-pull-request.yml
- src/main/java/com/meoguri/linkocean/LinkoceanApplication.java
- src/main/java/com/meoguri/linkocean/configuration/security/SecurityConfiguration.java
- src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
- src/main/java/com/meoguri/linkocean/configuration/security/oauth/OAuth2AuthenticationSuccessHandler.java
- src/main/java/com/meoguri/linkocean/controller/user/UserController.java
- src/main/java/com/meoguri/linkocean/controller/user/dto/LoginSuccessResponse.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileService.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/vo/Email.java
- src/main/java/com/meoguri/linkocean/domain/user/repository/UserRepository.java
- src/main/resources/db/migration/V013__Alter_users_unique_constraints.sql
- src/test/java/com/meoguri/linkocean/domain/user/repository/UserRepositoryTest.java
-  Users table 변경 Unique key email -> email,oauthtype
-   CustomOAuth2UserService 수정 -> 성공 후 /login/success 호출
> [LO-75] Users table 변경 Unique key email -> email,oauthtype

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/UpdateBookmarkCommand.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- 북마크 수정 서비스 개발
- 북마크 수정을 서비스 개발했습니다.
- 북마크 수정 테스트에서 중복 코드를 줄이기 위해 `@Nest`를 이용했슴돠 (하하꺼 배낌..)
- `Fixture`에 유연성을 추가해줬습니다.
> [LO-82] 북마크 수정 서비스 개발

- src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
- src/main/java/com/meoguri/linkocean/controller/profile/dto/CreateProfileRequest.java
- src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
- src/main/java/com/meoguri/linkocean/controller/user/dto/LoginSuccessResponse.java
- src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
- Profile 등록 API 개발, 테스트 & /login/success API 테스트 작성
@ndy2 , @hyuk0309
> [LO-51] Profile 등록 API 개발, 테스트 & /login/success API 테스트 작성

- src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/Url.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByUrlQuery.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepository.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/main/java/com/meoguri/linkocean/domain/user/repository/UserRepository.java
- src/test/java/com/meoguri/linkocean/configuration/security/oauth/OAuthAttributesTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadataTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/entity/UrlTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/EmailTest.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
- src/test/java/com/meoguri/linkocean/domain/user/repository/UserRepositoryTest.java
> [LO-93] vo 패키지 제거

- src/main/java/com/meoguri/linkocean/controller/bookmark/ReactionController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
- 리액션 Service test 추가 했습니다.
- 리액션 Service interface 수정이 있었습니다.
-  Service Controller API 추가 및 test 추가 했습니다.
> [LO-91] 리액션 요청 API

- src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImplTest.java
- 별거 없어요!
@NewEgoDoc, @hyuk0309
> [LO-98] 내 프로필 조회 category NPE 해결

- src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
- ReactionServiceImpl 리팩토링 진행하였습니다.
- Service Controller API test baseUrl 적용하였습니다.
> [LO-91] 리액션 API 리팩토링

- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
상세 조회 이름 변경
s 로만 구문하니까 목록조회랑 너무 햇갈리네요
아직 진행하진 않았지만 
내프로필 조회 GetMyProfile
프로필 조회 (id 로) GetDetailedProfile
프로필 목록 조회 (머구리찾기) GetProfiles 로 네이밍 잡을 생각입니다.
> [LO-101] rename GetBookmarkXXX -> GetDetailedBookmarkXXX

- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/notification/entity/noti/BookmarkNoti.java
- src/main/java/com/meoguri/linkocean/domain/notification/entity/noti/ProfileNoti.java
- src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationService.java
- src/main/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQuery.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/notification/service/NotificationServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
- 공유 알림 생성, 알림 조회 서비스
- 하면서 프로필 쌍으로 팔로우 여부 조회하는 쿼리를 만들어 북마크 서비스와 공유 알림 서비스에 적용하였습ㄴ디ㅏ.
---
- MongoDb 에 대해서 서비스의 응답을 Dto 를 적용할 적절한 방식이 생각이 안나 그냥 엔티티를 반환 하였습니다.
> [LO-66] 공유 알림 생성, 알림 조회 서비스

- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/support/GetBookmarkQueryParams.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/BookmarkByUsernameSearchCond.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/OtherBookmarkSearchCond.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- 다른 사람 북마크 조회 & 피드 북마크 조회 컨트롤러 껍데기 개발
- 다른 사람 북마크 조회 & 피드 북마크 조회 껍데기 컨트롤러를 개발했습니다.
- 해당 endpoint로 API를 호출하면 Dummy 데이터가 반환됩니다.
> [LO-110] 다른 사람 북마크 조회 & 피드 북마크 조회 컨트롤러 껍데기 개발

- src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
- src/main/java/com/meoguri/linkocean/controller/profile/dto/UpdateProfileRequest.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
-  Profile update API 개발
- Profile update logic 수젖ㅇ
@ndy2 ,@hyuk0309
> [LO-111] Profile update API 개발

- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- 북마크 삭제 Service & Test
- 북마크 삭제 Controller & Test
- 
@NewEgoDoc, @hyuk0309
> [LO-57] 북마크 삭제 API 개발

- src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
-queryParam 한글 이슈 테스트 깨짐 이슈
@ndy2 , @NewEgoDoc, @hyuk0309
> [LO-113] queryParam 한글 이슈

- src/main/java/com/meoguri/linkocean/controller/CustomRestControllerAdvice.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- 로그 레밸 설정 & 북마크 상세 조회 이슈 해결
- 개발 서버에서 로그를 통해 에러를 모니터링 해야하는데 로그 레밸이 디버그라서 운영하면서 확인하는데 어려움이 있어 로그 레밸을 변경했습니다.
- 북마크 상세조회시 userId 넘기는 이슈가 있어 수정했습니다.
> [LO-122] 로그 레밸 설정 & 북마크 상세 조회 이슈 해결

- src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/service/TagServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- Bookmark register, update addTag 방식 통일 및 테스트 파급효과 처리
- 내용은 별 것 없으나 테스트 특히 북마크 생성 부분에 변경이 있어서 테스트 파급효과를 처리했습니다.
-  나중에 Conflict 대잔치날까봐 빨리 PR 날립니다!
@ndy2 ,@NewEgoDoc, @hyuk0309
> [LO-121] Bookmark register, update addTag 방식 통일 및 테스트 파급효과 처리

- build.gradle
- src/main/java/com/meoguri/linkocean/configuration/SecurityConfiguration.java
- src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
- src/main/resources/logback-dev.xml
- error log slack 연동 간단한 작업입니다!
- config: application-dev.yml에 slack 연동 추가
- logback 추가, 자잘한 수정
@ndy2 ,@NewEgoDoc, @hyuk0309
> [LO-237] error log slack 연동

- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/util/Join.java
- src/main/java/com/meoguri/linkocean/util/JoinInfoBuilder.java
- src/main/java/com/meoguri/linkocean/util/Querydsl4RepositorySupport.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- 중복 url 확인 로직 리팩토링, 픽스
- joinIf on 절 매번 동작 할 수 있도록 변경
- 할게 너무 많이 보이네요...
> [LO-128] 중복 url 확인 로직 리팩토링, 픽스/ joinIf on 절 매번 동작 할 수 있도록 변경

- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/GetDetailedBookmarkResult.java
- src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
-1. 테스트시 링크 메타데이터 모킹 
-2. 북마크 상세조회 응답 bookmarkId 추가
테스트가 꽤 빨라진거 같네요
> [LO-131] 1. 테스트시 링크 메타데이터 모킹 2. 북마크 상세조회 응답 bookmarkId 추가

- src/main/java/com/meoguri/linkocean/configuration/resolver/GetBookmarkQueryParamsArgumentResolver.java
- src/main/java/com/meoguri/linkocean/configuration/resolver/GetProfileQueryParamsArgumentResolver.java
- src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/meoguri/linkocean/configuration/security/jwt/SecurityUser.java
- src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTag.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Favorite.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Follow.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/main/java/com/meoguri/linkocean/exception/LinkoceanRuntimeException.java
- src/main/java/com/meoguri/linkocean/exception/Preconditions.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/entity/ProfileTest.java
- 로그, 예외 처리 강화
- CustomRestControllerAdvice 작업, 추가적인 로깅 aop 설정 작업 등이 이루어 져야 합니다.
> [LO-137] 로그, 예외 처리 강화

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Tag.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/Link.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Follow.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/Email.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- 간단한 작업이었씁니다 그냥 주석 추가에용
@ndy2 , @NewEgoDoc, @hyuk0309
> [LO-139] Entity 주석 추가 초벌

- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetBookmarksResponse.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetDetailedBookmarkResponse.java
- src/main/java/com/meoguri/linkocean/controller/bookmark/dto/GetFeedBookmarksResponse.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/Category.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/test/java/com/meoguri/linkocean/controller/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
> [LO-141] 북마크 피드조회 서비스, 영속성 테스트 

- src/main/resources/db/data/insert_bookmark.sql
- src/main/resources/db/data/insert_linkmetadata.sql
> [LO-145] 더미데이터 마는 sql script

- src/main/java/com/meoguri/linkocean/controller/bookmark/BookmarkController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/dto/BookmarkFindCond.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/util/Fixture.java
- 즐겨찾기 로직 수정
- 전에 on 절을 하나 지웠다고 말씀드렸었는데 그걸 다시 돌려도 이상한 부분이 있더라고요?
그래서 일단 제생각에 올바른 방향으로 변경을 했는데 쿼리 로직을 꼼꼼하게 확인한번 해주시면 감사하겠습니다...
- 아니면 내일 북마크, 프로필 조회의 모든 쿼리에 대해서 한번 같이 읽으면서 점검하는 시간을 가졌으면 좋겠네요
> [LO-144] 즐겨찾기 로직 수정

- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- 북마크 오픈타입  이슈 해결 
- 이미 해결돼서 부족한 테스트만 추가했습니다.
> [LO-150] 북마크 오픈타입  이슈 해결 (이미 해결됨?!)

- src/main/java/com/meoguri/linkocean/controller/bookmark/ReactionController.java
- src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTag.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Favorite.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Reaction.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/vo/Category.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/ReactionCommand.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/Link.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/entity/LinkMetadata.java
- src/main/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByUrlQuery.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/FavoriteCategory.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Follow.java
- src/main/java/com/meoguri/linkocean/domain/profile/entity/Profile.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/ProfileServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/User.java
- src/main/java/com/meoguri/linkocean/domain/user/service/UserService.java
- src/main/java/com/meoguri/linkocean/domain/user/service/UserServiceImpl.java
- src/main/resources/db/migration/V015__Alter_Columns.sql
- src/main/resources/db/migration/V016__Alter_Foregin_Key_users_profile.sql
- src/test/java/com/meoguri/linkocean/LinkoceanApplicationTests.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/ReactionServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
- src/test/resources/application.yml
- flyway migration & reaction test 보강
-  **프로필 아이디, 유저 아이디 외래키 위치 스왑**
- column length 255 -> 700
- bookmark.url 255 -> 700
- link_metadata.link 255 -> 700
- link_metadata.image 255 -> 700
- profile.image 255 -> 700
- link_metadata.title -> 255 -> 500
> [LO-152] flyway migration & reaction test 보강

- build.gradle
- src/test/java/com/meoguri/linkocean/controller/bookmark/BookmarkControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/CategoryControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/FavoriteControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/bookmark/ReactionControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/linkmetadata/LinkMetadataControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/notification/NotificationControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/FollowControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/profile/ProfileControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/support/BaseControllerTest.java
- src/test/java/com/meoguri/linkocean/controller/support/RestDocsConfig.java
- src/test/java/com/meoguri/linkocean/controller/support/RestDocsTestSupport.java
- src/test/java/com/meoguri/linkocean/controller/user/LoginControllerTest.java
- RestDocs 세팅 추가
@ndy2 , @NewEgoDoc, @hyuk0309
> [LO-154] RestDocs 세팅 추가

- src/test/java/com/meoguri/linkocean/controller/restdocs/FavoriteDocsController.java
- src/test/java/com/meoguri/linkocean/controller/restdocs/ReactionDocsController.java
- reaction api restdocs, favorite restdocs 추가 했습니다
> [LO-159] Reaction & Favorite RestDocs 추가

- src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtProvider.java
- src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
- src/main/java/com/meoguri/linkocean/domain/user/entity/vo/OAuthType.java
- src/test/java/com/meoguri/linkocean/domain/user/entity/UserTest.java
- src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
- 소셜 로그인 타입에 GITHUB 추가
-  소셜 로그인 타입에 GITHUB 추가했습니다.
-  테스트 보강했습니다.
-  짜잘한 오타 수정했습니다.
> [LO-163] 소셜 로그인 타입에 GITHUB 추가

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Favorite.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkService.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/CategoryServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/TagServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/RegisterBookmarkCommand.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/dto/UpdateBookmarkCommand.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFavoriteQuery.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/BookmarkTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/FavoriteTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
-  Bookmark.profile -> Bookmark.writer
-  Favorite.owner -> Favorite.profile
> [LO-165] rename fields in entity

- build.gradle
- src/main/java/com/meoguri/linkocean/infrastructure/s3/S3Uploader.java
- src/test/java/com/meoguri/linkocean/infrastructure/s3/S3UploaderTest.java
- s3 적용에 대충 보니까 3단계의 개선이 필요한것 같습니다.
-  1단계 - original filename -> uuid
-  2단계 - test mocking
-  3단계 - 비동기 처리
1단계 진행하였고 2단계 진행을 위한 build.gradle 수정까지 진행했습니다
다음 PR 혹은 여기에 이어서 2단계, 3단계 진행하겠습니다.
> [LO-170] S3 적용 개선 1단계

- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Bookmark.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/entity/Favorite.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQuery.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepository.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/bookmark/service/FavoriteServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepository.java
- src/main/java/com/meoguri/linkocean/domain/profile/service/FollowServiceImpl.java
- src/main/java/com/meoguri/linkocean/exception/Preconditions.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/entity/FavoriteTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/BookmarkRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/CustomBookmarkRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/FavoriteRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/ReactionRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/persistence/TagRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/bookmark/service/BookmarkServiceImplTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/FindLinkMetadataByLinkQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/persistence/LinkMetadataRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/CheckIsFollowQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/CustomProfileRepositoryImplTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/FindProfileByIdQueryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/FollowRepositoryTest.java
- src/test/java/com/meoguri/linkocean/domain/profile/persistence/ProfileRepositoryTest.java
- src/test/java/com/meoguri/linkocean/test/support/persistence/BasePersistenceTest.java
- 나머지도 전부 적용했습니다.
-   코드양이 줄고 작성이 편해지는 장점이 있는거 같습니다.
- 자연스럽게 프로필, 사용자의 생성 및 영속성에 저장하는 로직이 한 곳으로 모이면서 deprecated 된 생성자, fixture 의 사용이 없어지는 장점이 있는거 같습니다.
> [LO-172] BasePersistenceTest 적용 완료

- src/main/java/com/meoguri/linkocean/configuration/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/meoguri/linkocean/configuration/security/oauth/CustomOAuth2UserService.java
- src/main/java/com/meoguri/linkocean/controller/user/LoginController.java
- src/main/java/com/meoguri/linkocean/domain/user/service/UserService.java
- src/main/java/com/meoguri/linkocean/domain/user/service/UserServiceImpl.java
- src/main/java/com/meoguri/linkocean/domain/user/service/dto/GetUserResult.java
- src/test/java/com/meoguri/linkocean/DependencyRuleTest.java
- src/test/java/com/meoguri/linkocean/domain/user/service/UserServiceImplTest.java
- src/test/java/com/meoguri/linkocean/test/support/service/BaseServiceTest.java
- 사용자 쪽 리팩토링
- BaseServiceTest 를 사용자 쪽 부터 쭉 밀려고 하니까 바꾸면 좋을것 같은 부분이 많이 보여서 사용자 쪽만 일단 밀고 한번 끊었습니다.
- 실수로 이 4개 커밋 분을 바로 dev 에 푸시 해버렸습니다..
-  확인 용으로 LO-176 을 base 로 남깁니다.
- 다행히 빌드는 잘 되고 변경분도 많지 않습니다.
> [LO-177] 사용자 쪽 리팩토링

- .github/workflows/dev-ci-cd.yml
> [LO-195] 개발 서버 CI/CD 구축

- .gitignore
- 개발서버 무료 https 적용 
- 이걸로 될까요?
> [LO-193] 개발서버 무료 https 적용 

- .github/workflows/dev-ci-cd.yml
> [LO-199] Dev CI-CD 포트번호 수정

- src/main/java/com/meoguri/linkocean/controller/profile/ProfileController.java
- src/main/java/com/meoguri/linkocean/domain/profile/command/service/ProfileImageUploader.java
- src/main/java/com/meoguri/linkocean/infrastructure/s3/S3ProfileImageUploader.java
- src/test/java/com/meoguri/linkocean/DependencyRuleTest.java
- src/test/java/com/meoguri/linkocean/domain/linkmetadata/service/LinkMetadataServiceImplTest.java
-  s3uploader DIP 에도 dip 를 적용했습니다.
-  dependency rule test 도 부활시켰습니다.
> [LO-210] s3uploader DIP

- src/main/java/com/meoguri/linkocean/configuration/WebConfiguration.java
- 페이지 사이즈 상한선 변경
- 페이지 사이즈 상한선을 8에서 20으로 변경했습니다. 이유는 UI 변경 때문입니다.
@ndy2
> [LO-233] 페이지 사이즈 상한선 변경
